package com.orgpilot.llm

import com.sun.net.httpserver.{HttpExchange, HttpHandler, HttpServer}
import java.io.OutputStream
import java.net.InetSocketAddress
import java.nio.charset.StandardCharsets

object Main:
  def main(args: Array[String]): Unit =
    val server = HttpServer.create(new InetSocketAddress("0.0.0.0", 9090), 0)
    server.createContext("/health", new TextHandler("{\"ok\":true}"))
    server.createContext("/generate-schema", new SchemaHandler())
    server.setExecutor(null)
    server.start()
    println("OrgPilot Scala LLM skeleton running on http://localhost:9090")

final class TextHandler(response: String) extends HttpHandler:
  override def handle(exchange: HttpExchange): Unit =
    sendJson(exchange, 200, response)

final class SchemaHandler extends HttpHandler:
  override def handle(exchange: HttpExchange): Unit =
    if exchange.getRequestMethod != "POST" then
      sendJson(exchange, 405, "{\"error\":\"Method not allowed\"}")
      return

    val requestBody = String(exchange.getRequestBody.readAllBytes(), StandardCharsets.UTF_8)
    val objectName = JsonLite.extractString(requestBody, "objectName").getOrElse("AI Generated Object")
    val schema = SchemaAdvisor.generate(objectName)
    sendJson(exchange, 200, schema)

private def sendJson(exchange: HttpExchange, status: Int, body: String): Unit =
  val bytes = body.getBytes(StandardCharsets.UTF_8)
  exchange.getResponseHeaders.add("Content-Type", "application/json; charset=utf-8")
  exchange.sendResponseHeaders(status, bytes.length)
  val os: OutputStream = exchange.getResponseBody
  os.write(bytes)
  os.close()

object JsonLite:
  def extractString(json: String, key: String): Option[String] =
    val pattern = ("\\\"" + key + "\\\"\\s*:\\s*\\\"([^\\\"]*)\\\"").r
    pattern.findFirstMatchIn(json).map(_.group(1))

object SchemaAdvisor:
  def apiName(label: String): String =
    val cleaned = label
      .replaceAll("[^A-Za-z0-9]+", "_")
      .replaceAll("_+", "_")
      .stripPrefix("_")
      .stripSuffix("_")
    val pascal = cleaned.split("_").filter(_.nonEmpty).map(w => w.head.toUpper + w.tail).mkString("_")
    if pascal.endsWith("__c") then pascal else s"${pascal}__c"

  def generate(objectName: String): String =
    val api = apiName(objectName)
    s"""
    {
      "objectLabel": "${escape(objectName)}",
      "objectPluralLabel": "${escape(objectName)}s",
      "objectApiName": "$api",
      "description": "Generated by local Scala LLM skeleton. Replace SchemaAdvisor with a real model/RAG pipeline.",
      "nameField": { "label": "Name", "type": "Text" },
      "sharingModel": "ReadWrite",
      "deploymentStatus": "Deployed",
      "enableReports": true,
      "enableActivities": true,
      "enableSearch": true,
      "fields": [
        { "label": "Status", "apiName": "Status__c", "type": "Picklist", "values": ["New", "Active", "Inactive"] },
        { "label": "External Reference", "apiName": "External_Reference__c", "type": "Text", "length": 120, "externalId": true },
        { "label": "Notes", "apiName": "Notes__c", "type": "LongTextArea", "length": 32768, "visibleLines": 5 }
      ]
    }
    """.trim

  private def escape(value: String): String =
    value.replace("\\", "\\\\").replace("\"", "\\\"")
